lwr:
  # Publish all joint states -----------------------------------
  kuka_joint_state_controller:
    type: lwr_controllers/KUKAJointStateController
    publish_rate: 100  
    root_name: lwr_base_link
    tip_name: lwr_peg_link

  #   Joint Torque Impedance Controllers
  joint_controllers:
    type: lwr_controllers/JointControllers
    root_name: lwr_base_link
    tip_name: lwr_peg_link
    max_qdot: 1.0
    publish_rate: 100
    max_ee_dt : 1
    max_ee_f : 5
    max_qdot : 3

  joint_position_impedance_controller:
    type: lwr_controllers/JointPositionImpedanceController
    publish_rate: 100  
    root_name: lwr_base_link
    tip_name: lwr_7_link
    default: true
    joints: 
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint

